from vllm import SamplingParams



PROMPT_TEMPLATES = {
    "ours": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen2.5-VL-7B": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen3-VL-4B-Instruct":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen3-VL-4B-Thinking":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen3-VL-8B-Instruct":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen3-VL-8B-Thinking":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "gpt-5.1": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "gpt-5.2": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "gemini-3-pro": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",
    
    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "gemini-3-flash": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Llama-3.2-11B-Vision-Instruct":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen3.5-35B-A3B":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Qwen3.5-9B":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nPlease break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nAfter your analysis, output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "InternVL3.5-8B":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "Step3-VL-10B":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "GLM-4.6V-Flash":{
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "gpt-5.4": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "gemini-3.1-pro": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
    "opus-4.6": {
    "think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nLet's think step by step and output the final answer in the required format.\nFirst, you need to output your detailed reasoning in <think> tags. In this reasoning, please break down the caption into its key components (objects, attributes, relationships) and verify each one against the image. If a component is a hallucination, clearly state *why*.\nSecond, you need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<think> [Your step-by-step analysis] </think> <result> [The tagged caption OR \"NO HALLUCINATION\"] </result>",

    "no_think": "Here is an image and its image caption is: {caption}\nYour task is to act as a meticulous visual verifier. You must judge whether the image caption contains 'hallucinations'.\nA 'hallucination' is defined as any word or phrase describing an object, attribute, relationship, or other visual content that is **verifiably incorrect** or **not visually present** in the image.\nYou need to output the final verification result in <result> </result> tags following these strict rules:\n1. If there is **no hallucination**, output exactly: <result>NO HALLUCINATION</result>\n2. If there is a hallucination, output the original caption but enclose the specific hallucinated word or phrase in <HALLUCINATION> </HALLUCINATION> tags. **CRITICAL: Do NOT correct, rewrite, or remove the hallucinated words.** You must preserve the original text exactly, only adding tags around the incorrect parts.\n\nHere is the exact output format to follow:\n<result> [The tagged caption OR \"NO HALLUCINATION\"] </result>"
},
}



def get_sampling_params(model_name, seed):
    if model_name == "ours":
        sampling_params = SamplingParams(
            temperature=0.01,   
            seed=seed,                
            repetition_penalty=1.05,  
            max_tokens=2048,          
            stop=["<|endoftext|>", "<|im_end|>"]   
        )

    elif model_name == "Qwen2.5-VL-7B":
        sampling_params = SamplingParams(
            temperature=0.01,   
            seed=seed,                
            repetition_penalty=1.05,  
            max_tokens=2048,          
            stop=["<|endoftext|>", "<|im_end|>"]   
        )

    elif model_name == "Qwen3-VL-4B-Instruct":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,  
            max_tokens=2048,          
            stop=["<|endoftext|>", "<|im_end|>"]   
        )

    elif model_name == "Qwen3-VL-8B-Instruct":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=2048,
            stop=["<|endoftext|>", "<|im_end|>"] 
        )
    elif model_name == "Qwen3-VL-8B-Thinking":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|endoftext|>", "<|im_end|>"],
        )
    elif model_name == "Qwen3.5-9B":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|endoftext|>", "<|im_end|>"],
            skip_special_tokens=False,
        )
    elif model_name == "InternVL3.5-8B":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|endoftext|>", "<|im_end|>"],
            skip_special_tokens=False,
        )
    elif model_name == "Llama-3.2-11B-Vision-Instruct":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|eot_id|>", "<|end_of_text|>"],
        )
    elif model_name == "Qwen3.5-35B-A3B":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|endoftext|>", "<|im_end|>"],
        )
    elif model_name == "Step3-VL-10B":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|endoftext|>", "<|im_end|>"],
        )
    elif model_name == "GLM-4.6V-Flash":
        sampling_params = SamplingParams(
            seed = seed,
            temperature=0.1,
            repetition_penalty=1.05,
            max_tokens=40960,
            stop=["<|endoftext|>", "<|user|>", "<|observation|>"],
        )

    return sampling_params


def get_transformers_generate_kwargs(model_name, seed):
    """Convert sampling params to transformers model.generate() kwargs."""
    if model_name == "Qwen3.5-35B-A3B":
        return {
            "max_new_tokens": 40960,
            "temperature": 0.1,
            "repetition_penalty": 1.05,
            "do_sample": True,
        }
    elif model_name == "GLM-4.6V-Flash":
        return {
            "max_new_tokens": 40960,
            "temperature": 0.1,
            "repetition_penalty": 1.05,
            "do_sample": True,
        }
    elif model_name == "InternVL3.5-8B":
        # InternVL model.chat() 接受 generation_config dict
        return {
            "max_new_tokens": 40960,
            "temperature": 0.6,
            "repetition_penalty": 1.05,
            "do_sample": True,
        }
    else:
        raise ValueError(f"Unknown transformers model: {model_name}")


# generic prompt construction function
def create_prompt(model_name, use_think, input_caption):
    """Construct the prompt for the model.
    Args:
        model_name: The name of the model.
        use_think: Whether to use the CoT prompt.
        input_caption: The original caption of the image.
    """
    mode_key = "think" if use_think else "no_think"
    
    # error check: ensure model and mode are in PROMPT_TEMPLATES
    if model_name not in PROMPT_TEMPLATES:
        raise ValueError(f"PROMPT_TEMPLATES dictionary does not contain model: {model_name}")
        
    template = PROMPT_TEMPLATES[model_name][mode_key]
    
    # replace the placeholder, the placeholder is {caption} in the prompt.json file
    return template.format(caption=input_caption)